<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $locations = [
            'OFICINA ADMINISTRATIVA',
            'CABINA TEATRO GALPON',
            'BOLETERIA 1 - TEATRO GALPON',
            'PCYMT',
            'BOLETERIA PRINCIPAL ATRIO',
            'ENTRE BAÑOS ATRIO',
            'BOLETERIA MULTIPROPOSITO',
            'ENTRADA OFICINA GALPON',
            'PASILLO GUARDAROPIA',
            'FRENTE PUERTA DE VIDRIO MULTIPROPOSITO',
            'SALIDA DE COCINETA GRANDE Y ENTRADA ALMACEN DE HERRAMIENTAS',
            'ENTRADA DE VIDRIO PORTON GALPON',
            'OFICINA GALPON',
            'INTERIOR CABINA DE TEATRO GALPON',
            'TEATRO GALPON',
            'ENTRADA GRADA TEATRO GALPON',
            'LADO IZQUIERDO GRADAS',
            'PASILLO CAMERINOS',
            'DESAGUE EMPLEADOS',
            'SALA DE PANELES ELECTRICOS Y DINAMICOS',
            'GRADAS LADO IZQUIERDO ESCENARIO',
            'BAÑO BAJO ESCENARIO',
            'SALIDA MULTIPROPOSITO',
            'ENCIMA TABLERO LADO DERECHO ESCENARIO',
            'LADO IZQUIERDO ESCENARIO',
            'SALIDA CAMERINO 3 LADO DERECHO ESCENARIO',
            'SALIDA A PARQUEO BAÑO 1',
            'BAÑO 2 ENTRADA FUERA',
            'BAÑO 1 ENTRADA',
            'BAÑO 3 ENTRADA',
            'BAÑO 4 FUERA',
            'SALIDA B A PARQUEO BAÑO 4',
            'OFICINAS DEL PARQUE',
            'CUARTO TABLERO ESCENARIOS',
            'DEPOSITO PARQUEO BAJO ESCENARIO',
            'SUBIENDO GRADAS A GALPON',
            'VIGILANCIA ATRIO',
            'INFORMACION ATRIO',
            'TAYPI',
            'CUARTO VALORES BOLETERIA PRINCIPAL',
            'BOLETERIA PARQUEO',
            'ENFERMERIA',
            'BAÑO 1 VARONES',
            'BAÑO 2 VARONES',
            'BAÑO 2 ALMACEN VARONES',
            'BAÑO 2 ALMACEN MUJERES',
            'BAÑO 1 MUJERES',
            'BAÑO ATRIO MUJERES',
            'BAÑO ATRIO DISCAPACITADOS',
            'PASILLO BOLETERIA ATRIO',
            'BAÑO 4 MUJERES',
            'TIERRA BAJAS',
            'BAÑO 3 ENTRADA RACK',
            'BAÑO 3 VARONES',
            'BAÑO 4 VARONES',
            'BAÑO 4 ENTRADA AFUERA',
            'PUERTA VIGILANCIA ATRIO',
            'PUERTA INFORMACIONES',
            'PUERTA DE BOLETERIA PRINCIPAL ATRIO',
            'VALORES BOLETERIA PRINCIPAL ATRIO',
            'CUARTO DE RACK LADO DE GUARDAROPIA',
            'CUARTO RACK LADO GUARDAROPIA',
            'ENTRADA ALMACEN HERRAMIENTAS',
            'ENTRADA ALMACEN SISTEMAS',
            'CUARTO TABLEROS MULTIPROPOSITO',
            'CUARTO TELECOM',
            'INGRESO DEPOSITO PARQUE',
            'INGRESO DEL DEPOSITO PARQUE A DESAGUE EMPLEADOS',
            'BAÑO 1 RACK TABLEROS',
            'PASILLO CAFETERIA LADO PORTON GALPON',
            'GALPON COCINETA GRANDE',
            'PASILLO DE ALMACEN DE SISTEMAS COMPLEMENTARIOS',
            'PASILLO COMPLEMENTARIO DE ENTRADA GALPON',
            'CAMERINO LADO ALMACEN SISTEMAS COMPLEMENTARIOS',
            'PASILLO ALMACEN DE SISTEMAS COMPLEMENTARIOS ENTRADA GALPON',
            'BAÑO CAMERINO P-12',
            'FRENTE CAMERINO P-13',
            'BAÑO VARONES MULTIPROPOSITO',
            'FRENTE A BAÑOS MULTIPROPOSITO',
            'FRENTE CUARTO TABLEROS MULTIPROPOSITO',
            'FRENTE BOLETERIA MULTIPROPOSITO',
            'ALMACEN DE SISTEMAS MULTIPROPOSITO',
            'BAÑO MUJERES ATRÁS DE GUARDAROPIA',
            'BAÑO VARONES ATRÁS DE GUARDAROPIA',
            'PASILLO BAÑOS GUARDAROPIA',
            'CUARTO RACK FRENTE BAÑO VARONES LADO GUARDAROPIA',
            'DEPOSITO FRENTE BAÑO VARONES LADO GUARDAROPIA',
            'FRENTE A GRADAS TEATRO Y GUARDAROPIA',
            'INTERIOR BUTACA GALPON',
            'ESCENARIO GALPON',
            'INGRESO GRADAS A TEATRO GALPON',
            'ENTRADA CAFETERIA COCINETA GRANDE',
            'ENTRADA ALMACEN PASILLO',
            'ENTRADA DE PUERTA DE VIDRIO MULTIPROPOSITO',
            'INGRESO A TEATRO GALPON ENTRE LAS 2 PUERTAS DE ENTRADAS',
            'INGRESO CABINA TEATRO GALPON',
            'TEATRO GALPON P-13',
            'ENTRADA PORTON GALPON',
            'BUTACAS GALPON',
            'FRENTE COCINETA PEQUEÑA MULTIPROPOSITO',
            'SIMPI (P-M1)',
            'JUCUMANIA',
            'CASA EKEKO',
            'SALA MULTIPLE',
            'CAMERINO 1',
            'CAMERINO 2',
            'CAMERINO 3',
            'CAMERINO 4',
            'TEATRO GALPON P-12',
            'ALMACEN PASILLO',
            'CAMERINO 3 (NIVEL DEL PARQUEO)',
            'POR CAMERINO P-12',
            'ALMACEN DE HERRAMIENTAS',
            'SALA OPERACIONES TEATRO GALPÓN',
            'DEPOSITO LIMPIEZA',
            'CUARTO TAYPI',
            'AMBIENTE TAYPI',
            'ALMACEN DESAHOGO',
            'SALA MULTIPROPÓSITO',
            'CUARTO DE PASANTES',
            'INGRESO AL PARQUE',
            'ALMACEN DE PASANTES',
            'PARQUE EXTERIOR',
            'ALMACEN 2',
            'ALMACEN 3',
            'ALMACEN 4',
            'ROTATORIO DENTRO DEL PARQUE',
            'CAMERINO P-12',
            'TEATRO GALPON P-14',
        ];

        $now = Carbon::now();

        $locationRecords = array_map(function($name) use ($now) {
            return [
                'name' => $name,
                'description' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $locations);

        DB::table('locations')->insert($locationRecords);
    }
}
