version: '3.4'

services:
  sisinventario:
    image: sisinventario
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
